//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendencieLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceListDbEntities : DbContext
    {
        public AttendanceListDbEntities()
            : base("name=AttendanceListDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseInfo> CourseInfoes { get; set; }
        public virtual DbSet<NonCourseDay> NonCourseDays { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Participants_Courses> Participants_Courses { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Teachers_Courses> Teachers_Courses { get; set; }
        public virtual DbSet<TimeRegistration> TimeRegistrations { get; set; }
    }
}
