//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_List
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseInfo()
        {
            this.NonCourseDays = new HashSet<NonCourseDay>();
            this.Participants_Courses = new HashSet<Participants_Courses>();
            this.Teachers_Courses = new HashSet<Teachers_Courses>();
            this.TimeRegistrations = new HashSet<TimeRegistration>();
        }
    
        public int ID { get; set; }
        public string CourseInstitution { get; set; }
        public string Course { get; set; }
        public string ContactPerson { get; set; }
        public string Location { get; set; }
        public Nullable<int> OeNumber { get; set; }
        public int CourseCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NonCourseDay> NonCourseDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants_Courses> Participants_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teachers_Courses> Teachers_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeRegistration> TimeRegistrations { get; set; }
    }
}
